name: CI Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fix eslint permissions (ACT only)
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run linter
        run: npx eslint .

      - name: Build project
        run: npm run build

      - name: Fix jest permissions (ACT only)
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests with coverage
        run: npm test

      - name: Enforce coverage threshold
        run: |
         echo "Verificando cobertura con Node"

         node -e "
         const fs = require('fs');
         const summary = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8'));
         const coverage = summary.total.lines.pct;

         console.log('Cobertura actual:', coverage + '%');

          if (coverage < 80) {
          console.error('error: Cobertura menor al 80%');
          process.exit(1);
          } else {
          console.log('Esta bueno, Cobertura satisfactoria');
          }
          "



      - name: Enforce coverage threshold (Node only)
        run: |
         echo "Verificando umbrales de cobertura"

         node -e "
         const fs = require('fs');
         const coverage = JSON.parse(fs.readFileSync('./coverage/coverage-summary.json','utf-8'));

         const lines = coverage.total.lines.pct;
         const functions = coverage.total.functions.pct;
         const statements = coverage.total.statements.pct;
         const branches = coverage.total.branches.pct;

         console.log('Cobertura detectada:');
         console.log('Lines:', lines + '%');
         console.log('Functions:', functions + '%');
         console.log('Statements:', statements + '%');
         console.log('Branches:', branches + '%');

         if(lines < 80 || functions < 80 || statements < 80 || branches < 80){
         console.error('Esta malo Cobertura insuficiente');
         process.exit(1);
         } else {
         console.log('cumplio con la cobertura Cobertura correcta');
         }
         "

